# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: demo CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [opened, synchronize]

jobs:

  avoid_reduncy:
    runs-on: ubuntu-latest
    steps:
      - name: Cancelacion de Builds 
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{github.token}}
  
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-node@v6
      with:
          node-version: 20
          cache: "npm"
    - run: npm ci --legacy-peer-deps
    - run: npm run test


  build:
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-node@v6
      with:
          node-version: 20
          cache: "npm"
    - run: npm ci --legacy-peer-deps
    - run: npm run bundle
    - run: npm run build


  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Deploy a Vercel
      if: ${{github.event_name == 'push'}}
      run: npx vercel --prod --yes --name=tp-ci-cd --token=${{ secrets.VERCEL_TOKEN }}
      env:
        VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }} 
    
  feedback:
    needs: [deploy, build, tests]
    if: always() # Siempre se ejecuta, sin importar el resultado de los trabajos anteriores 
    runs-on: ubuntu-latest
    steps: 
    - name: Notificar éxito a Discord
      if: needs.tests.result == 'success' && needs.build.result == 'success' && needs.deploy.result == 'success'
      run: |
        curl -X POST ${{ secrets.DISCORD_WEBHOOK }} \
        -H "Content-Type: application/json" \
        -d '{"content": "✅ Pipeline exitosa! Los tests pasaron y el deploy se realizó correctamente."}'

    - name: Notificar fallo a Discord
      if: needs.tests.result != 'success' || needs.build.result != 'success' || needs.deploy.result != 'success'
      run: |
        curl -X POST "${{ secrets.DISCORD_WEBHOOK }}" \
          -H "Content-Type: application/json" \
          -d "{\"content\": \"❌ Pipeline fallida! Algo salió mal en los tests o el deploy.\\nRepo: ${{ github.repository }}\\nRef: ${{ github.ref }}\\nCommit: ${{ github.event.head_commit.message }}\\nRun: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}\"}"
